### ISSUE TITLE
`floatNext` seems to produce problematic values during shrink

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#1181]
## 🐛 Bug Report

Several warnings have been raised by our unit tests around `floatNext`. The feature will have to be investigated closer:

```txt
FAIL test/unit/check/arbitrary/FloatNextArbitrary.spec.ts
  ● FloatNextArbitrary › floatNext › Is valid arbitrary? › Should produce strictly smaller values along the shrink path

    Property failed after 91 tests
    { seed: 1604759799, path: "90:0:33:0:0:2:2:2:3:3", endOnFailure: true }
    Counterexample: [[null,{"min":0,"max":0}],996968860,[0]]
    Shrunk 9 time(s)
    Got error: Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

    Stack trace: Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      75 |             shrinkable = shrinkable.shrink().getNthOrLast(id);
      76 |             if (shrinkable !== null) {
    > 77 |               expect(isStrictlySmallerValue(shrinkable.value, prevValue)).toBe(true);
         |                                                                           ^
      78 |               prevValue = shrinkable.value;
      79 |             }
      80 |             id = (id + 1) % shrinkPath.length;

      at test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts:77:75
```
More https://github.com/dubzzz/fast-check/pull/1174/checks?check_run_id=1440362245

```txt
FAIL test/unit/check/arbitrary/FloatNextArbitrary.spec.ts
  ● FloatNextArbitrary › floatNext › Is valid arbitrary? › Should produce strictly smaller values along the shrink path

    Property failed after 48 tests
    { seed: 942444693, path: "47:10:11:11", endOnFailure: true }
    Counterexample: [[null,{"min":1.6815581571897805e-44,"max":1.961817850054744e-44}],584788236,[0]]
    Shrunk 3 time(s)
    Got error: Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

    Stack trace: Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      75 |             shrinkable = shrinkable.shrink().getNthOrLast(id);
      76 |             if (shrinkable !== null) {
    > 77 |               expect(isStrictlySmallerValue(shrinkable.value, prevValue)).toBe(true);
         |                                                                           ^
      78 |               prevValue = shrinkable.value;
      79 |             }
      80 |             id = (id + 1) % shrinkPath.length;

      at test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts:77:75
```
More https://github.com/dubzzz/fast-check/pull/1177/checks?check_run_id=1440398966

```txt
FAIL test/unit/check/arbitrary/FloatNextArbitrary.spec.ts
  ● FloatNextArbitrary › floatNext › Is valid arbitrary? › Should produce strictly smaller values along the shrink path

    Property failed after 55 tests
    { seed: 1791053047, path: "54:3:6:8:7:7:7:7:7:7:7:7:7:7:7:7:7:7:7:7:7:7:8:8:9:9", endOnFailure: true }
    Counterexample: [[47,{"min":Number.NEGATIVE_INFINITY,"max":0}],20,[0]]
    Shrunk 25 time(s)
    Got error: Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

    Stack trace: Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      75 |             shrinkable = shrinkable.shrink().getNthOrLast(id);
      76 |             if (shrinkable !== null) {
    > 77 |               expect(isStrictlySmallerValue(shrinkable.value, prevValue)).toBe(true);
         |                                                                           ^
      78 |               prevValue = shrinkable.value;
      79 |             }
      80 |             id = (id + 1) % shrinkPath.length;

      at test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts:77:75
```
More https://github.com/dubzzz/fast-check/pull/1180/checks?check_run_id=1440403225

**Comment by dubzzz** [comment]
Fixed
