### ISSUE TITLE
Unhandled Assertion errors in Async properties

### ISSUE THREAD

**Issue by julianmrodri** [dubzzz/fast-check#2332]
## 💬 Question and Help

I'm facing a strange situation. Im building a Model-based test using `async` properties, and my assertions/expects instead of making the test fail they show up with an error as Unhandled promises. Do I need to do something different when working async?

This is an example of a Test:

```
 it('Should run commands correctly', async function () {
    await fc.assert(
      fc.asyncProperty(TokenLibCommands, async (commands) => {
        const real = new TokenLibCallerImplem(token, caller, minter)
        const model = new TokenLibModel()
        fc.asyncModelRun(() => ({ model, real }), commands)
      })
    )
  })
```

Inside of the command that Fails I just put a simple assertion (no other checks)

```
export class TransferCommand implements TokenLibCommand {
  constructor(readonly amount: BigNumber) {}
  async check(m: TokenLibModel) {
    return true
  }
  async run(m: TokenLibModel, p: TokenLibCaller) {
    assert.equal(1, 2) // also tried with `expect(1).equal(2)` same behavior
  }
  toString() {
    return `Transfer("${this.amount}")`
  }
}
```
But instead of failing the test I get the test to **PASS** and the following errors:

```
(node:90651) UnhandledPromiseRejectionWarning: AssertionError: expected 1 to equal 2
    at TransferCommand.run (/Users/julian/Documents/Projects/protocol/test/cross-implementation/system0-model/TransferCommand.ts:16:12)
    at CommandWrapper.run (/Users/julian/Documents/Projects/protocol/node_modules/fast-check/lib/check/model/commands/CommandWrapper.js:28:25)
    at runAsync (/Users/julian/Documents/Projects/protocol/node_modules/fast-check/lib/check/model/ModelRunner.js:48:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
(node:90651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 204)
```

What could be going on? If i change the assert to ` assert.equal(1, 1)` everything runs ok. Which is the way to properly check for assertions in async mode? Im having similar behavior with `expect(...)`.

Thanks!

**Comment by julianmrodri** [comment]
Worked like a charm! This missing await was driving me nuts. Thanks!
