### ISSUE TITLE
Invalid output for record

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#3065]
## 🐛 Bug Report

```txt
 FAIL test/unit/arbitrary/record.spec.ts
  ● record (integration) › should only produce correct values
    Property failed after 93 tests
    { seed: 1683444164, path: "92:0:87:86:86", endOnFailure: true }
    Counterexample: [-1081429049,undefined,Stream(…),[[{"key":"__proto__","valueStart":0,"kept":false}],{}]]
    Shrunk 4 time(s)
    Got error: Error: Expect: {} to be a correct value
    Got error: Error: expect(received).not.toBe(expected) // Object.is equality
    Expected: not false
    Stack trace: Error: Expect: {} to be a correct value
    Got error: Error: expect(received).not.toBe(expected) // Object.is equality
    Expected: not false
      172 |     delete previousValue.value;
      173 |     return arbitraryBuilder(...args);
    > 174 |   }
          |    ^
      175 |   function isStrictlySmallerInternal(v: T, extraParameters: U) {
      176 |     try {
      177 |       if (!('value' in previousValue)) {
      at assertCorrectness (test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:174:15)
      at test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:47:13
      at Property.predicate (lib/check/property/Property.js:16:86)
      at Property.run (lib/check/property/Property.generic.js:40:33)
      at runIt (lib/check/runner/Runner.js:16:30)
      at check (lib/check/runner/Runner.js:63:11)
      at Object.assert (lib/check/runner/Runner.js:67:17)
      at assertProduceCorrectValues (test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:41:8)
      at Object.<anonymous> (test/unit/arbitrary/record.spec.ts:190:62)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at throwIfFailed (lib/check/runner/utils/RunDetailsFormatter.js:128:11)
      at reportRunDetails (lib/check/runner/utils/RunDetailsFormatter.js:141:16)
      at Object.assert (lib/check/runner/Runner.js:71:52)
      at assertProduceCorrectValues (test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:41:8)
      at Object.<anonymous> (test/unit/arbitrary/record.spec.ts:190:62)
```

**Comment by dubzzz** [comment]
And potentially linked ones:

```txt
FAIL test/unit/arbitrary/record.spec.ts
  ● record › should call buildPartialRecordArbitrary with keys=requiredKeys when constraints defines valid requiredKeys
    Property failed after 30 tests
    { seed: 2054583010, path: "29:3:85:85:85", endOnFailure: true }
    Counterexample: [["__proto__",""],function(...args) {
      // With hash and stringify coming from fast-check
      /* [""] => true */
      /* ["__proto__"] => true */
      const outs = [true];
      return outs[hash('-21' + stringify(args)) % outs.length];
    }]
    Shrunk 4 time(s)
    Got error: Error: requiredKeys cannot reference keys that have not been defined in recordModel
    Stack trace: Error: requiredKeys cannot reference keys that have not been defined in recordModel
      at record (src/arbitrary/record.ts:712:13)
      at test/unit/arbitrary/record.spec.ts:67:41
      at Property.predicate (lib/check/property/Property.js:16:86)
      at Property.run (lib/check/property/Property.generic.js:40:33)
      at runIt (lib/check/runner/Runner.js:16:30)
      at check (lib/check/runner/Runner.js:63:11)
      at Object.assert (lib/check/runner/Runner.js:67:17)
      at Object.<anonymous> (test/unit/arbitrary/record.spec.ts:52:145)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at throwIfFailed (lib/check/runner/utils/RunDetailsFormatter.js:128:11)
      at reportRunDetails (lib/check/runner/utils/RunDetailsFormatter.js:141:16)
      at Object.assert (lib/check/runner/Runner.js:71:52)
      at Object.<anonymous> (test/unit/arbitrary/record.spec.ts:52:145)
  ● record (integration) › should produce the same values given the same seed
    Property failed after 23 tests
    { seed: -1774969207, path: "22:0:1:0:0:0:85", endOnFailure: true }
    Counterexample: [375571435,undefined,Stream(…),[[{"key":"__proto__","valueStart":0,"kept":true}],{"requiredKeys":["__proto__"]}]]
    Shrunk 6 time(s)
    Got error: Error: requiredKeys cannot reference keys that have not been defined in recordModel
    Stack trace: Error: requiredKeys cannot reference keys that have not been defined in recordModel
      at record (src/arbitrary/record.ts:712:13)
      at recordBuilder (test/unit/arbitrary/record.spec.ts:184:36)
      at test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:17:21
      at Property.predicate (lib/check/property/Property.js:16:86)
      at Property.run (lib/check/property/Property.generic.js:40:33)
      at runIt (lib/check/runner/Runner.js:16:30)
      at check (lib/check/runner/Runner.js:63:11)
      at Object.assert (lib/check/runner/Runner.js:67:17)
      at assertProduceSameValueGivenSameSeed (test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:15:8)
      at Object.<anonymous> (test/unit/arbitrary/record.spec.ts:187:71)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at throwIfFailed (lib/check/runner/utils/RunDetailsFormatter.js:128:11)
      at reportRunDetails (lib/check/runner/utils/RunDetailsFormatter.js:141:16)
      at Object.assert (lib/check/runner/Runner.js:71:52)
      at assertProduceSameValueGivenSameSeed (test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:15:8)
      at Object.<anonymous> (test/unit/arbitrary/record.spec.ts:187:71)
```
