### ISSUE TITLE
Some arbitraries still sensible to poisoning 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#3114]
## 🐛 Bug Report

See https://github.com/dubzzz/fast-check/runs/8162209609?check_suite_focus=true

**Comment by dubzzz** [comment]
Got:

```txt
FAIL test/e2e/Poisoning.spec.ts
  ● Poisoning (seed: 485664271) › should not be impacted by altered globals when using webFragments

    expect(received).toMatch(expected)

    Expected pattern: /Property failed after/
    Received string:  "c.charCodeAt is not a function"

      139 |     } catch (err) {
      140 |       interceptedException = err;
    > 141 |     }
          |      ^
      142 |
      143 |     // Assert
      144 |     restoreGlobals(); // Restore globals before running real checks

      at test/e2e/Poisoning.spec.ts:141:46

  ● Poisoning (seed: 485664271) › should not be impacted by altered globals when using webQueryParameters

    expect(received).toMatch(expected)

    Expected pattern: /Property failed after/
    Received string:  "c.charCodeAt is not a function"

      139 |     } catch (err) {
      140 |       interceptedException = err;
    > 141 |     }
          |      ^
      142 |
      143 |     // Assert
      144 |     restoreGlobals(); // Restore globals before running real checks

      at test/e2e/Poisoning.spec.ts:141:46

  ● Poisoning (seed: 485664271) › should not be impacted by altered globals when using webSegment

    expect(received).toMatch(expected)

    Expected pattern: /Property failed after/
    Received string:  "c.charCodeAt is not a function"

      139 |     } catch (err) {
      140 |       interceptedException = err;
    > 141 |     }
          |      ^
      142 |
      143 |     // Assert
      144 |     restoreGlobals(); // Restore globals before running real checks

      at test/e2e/Poisoning.spec.ts:141:46
```
