### ISSUE TITLE
dictionary of string values and keys produce "Unexpected value received: not an instance of Arbitrary"

### ISSUE THREAD

**Issue by mitre-tm** [dubzzz/fast-check#3368]
## 🐛 Bug Report

```bash
$ npm test

> test
> jest --coverage=true

 FAIL  ./reproduce.test.js
  foo
    ✕ bar (1 ms)

  ● foo › bar

    Unexpected value received: not an instance of Arbitrary

      4 |   it("bar", () => {
      5 |     fc.assert(
    > 6 |       fc.property(
        |          ^
      7 |         fc.dictionary(fc.string(), fc.string()),
      8 |         fc.string(),
      9 |         (_testValue, _somePrefix) => {},

      at assertIsArbitrary (node_modules/fast-check/lib/check/arbitrary/definition/Arbitrary.js:210:15)
          at Array.forEach (<anonymous>)
      at safeForEach (node_modules/fast-check/lib/utils/globals.js:137:25)
      at Object.property (node_modules/fast-check/lib/check/property/Property.js:15:31)
      at Object.property (reproduce.test.js:6:10)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.217 s, estimated 1 s
Ran all test suites.
```

## To Reproduce

Steps to reproduce:

```js
// reproduce.test.js
const fc = require("fast-check");

describe("foo", () => {
  it("bar", () => {
    fc.assert(
      fc.property(
        fc.dictionary(fc.string(), fc.string()),
        fc.string(),
        (_testValue, _somePrefix) => {},
        {
          seed: 1400789601,
          path: "67:2:2:2:3:3:7:6:6:7:7:7:5",
          endOnFailure: true,
        }
      )
    );
  });
});
```

```jsonc
// package.json
{
  "scripts": {
    "test": "jest --coverage=true"
  },
  "devDependencies": {
    "fast-check": "^3.3.0"
  },
  "dependencies": {
    "jest": "^29.2.2"
  }
}
```

```
$ npm install
$ npm test
```

## Expected behavior

I expected no exception to be thrown.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           |      3.3.0      |
| node                 |  18.12.0   |
| TypeScript\*         |   N/A        |

\*Only for TypeScript's users

**Comment by dubzzz** [comment]
You should try with:

```js
// reproduce.test.js
const fc = require("fast-check");

describe("foo", () => {
  it("bar", () => {
    fc.assert(
      fc.property(
        fc.dictionary(fc.string(), fc.string()),
        fc.string(),
        (_testValue, _somePrefix) => {},
      ),
      {
        seed: 1400789601,
        path: "67:2:2:2:3:3:7:6:6:7:7:7:5",
        endOnFailure: true,
      }
    );
  });
});
```

**Comment by dubzzz** [comment]
The seed parameter has to be defined on `assert` not `property`. Normally TypeScript should have highlighted such wrong usage 🤔

**Comment by dubzzz** [comment]
Closing the issue, it seems that the syntax was wrong
