### ISSUE TITLE
Replay issue detected during unit

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#3613]
## 🐛 Bug Report

Occurred with https://github.com/dubzzz/fast-check/pull/3610

```txt
 FAIL test/e2e/ReplayFailures.spec.ts
  ● ReplayFailures (seed: -1275879229) › fc.assert › Should start from the minimal counterexample given its path

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 0

      68 |         { seed: seed, path: out.counterexamplePath! }
      69 |       );
    > 70 |       expect(numValidCalls).toEqual(1);
         |                             ^
      71 |       expect(validCallIndex).toEqual(0);
      72 |       expect(out2.numRuns).toEqual(1);
      73 |       expect(out2.numShrinks).toEqual(0);

      at Object.<anonymous> (test/e2e/ReplayFailures.spec.ts:70:29)

  ● ReplayFailures (seed: -1275879229) › fc.assert › Should start from any position in the path

    expect(received).toEqual(expected) // deep equality

    Expected: 10
    Received: 7

      84 |         const outMiddlePath = fc.check(prop, { seed: seed, path: p });
      85 |         expect(outMiddlePath.numRuns).toEqual(1);
    > 86 |         expect(outMiddlePath.numShrinks).toEqual(out.numShrinks - idx + 1);
         |                                          ^
      87 |         expect(outMiddlePath.counterexamplePath).toEqual(out.counterexamplePath);
      88 |         expect(outMiddlePath.counterexample).toEqual(out.counterexample);
      89 |       }

      at Object.<anonymous> (test/e2e/ReplayFailures.spec.ts:86:42)

  ● ReplayFailures (seed: -1275879229) › fc.assert › Should only execute one test given path for failure and noShrink flag

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 3

       97 |         const p = segments.slice(0, idx).join(':');
       98 |         const outMiddlePath = fc.check(prop, { seed: seed, path: p, endOnFailure: true });
    >  99 |         expect(outMiddlePath.numRuns).toEqual(1);
          |                                       ^
      100 |         expect(outMiddlePath.numShrinks).toEqual(0);
      101 |         expect(outMiddlePath.counterexamplePath).toEqual(p);
      102 |       }

      at Object.<anonymous> (test/e2e/ReplayFailures.spec.ts:99:39)

  ● ReplayFailures (seed: -1275879229) › fc.assert › Should take initial path into account when computing path

    expect(received).toEqual(expected) // deep equality

    Expected: "11:1:2:4:5:7:6:0:2:2:6"
    Received: "11:1:2:4:5:7:31:3:4:4"

      112 |         const p = [...segments.slice(0, playOnIndex), offset].join(':');
      113 |         const outMiddlePath = fc.check(prop, { seed: seed, path: p });
    > 114 |         expect(outMiddlePath.counterexamplePath).toEqual(out.counterexamplePath);
          |                                                  ^
      115 |         expect(outMiddlePath.counterexample).toEqual(out.counterexample);
      116 |       }
      117 |     });

      at Object.<anonymous> (test/e2e/ReplayFailures.spec.ts:114:50)
```

**Comment by dubzzz** [comment]
Bug reproduced with:
`@dubzzz ➜ /workspaces/fast-check/packages/fast-check (main) $ export DEFAULT_SEED="-1275879229"`

- On master: 1b13264aa9a36dd55edab8d8f3baf04e00d1ab88

**Comment by dubzzz** [comment]
Regression introduced by 7b8948786ae7f15a65a485852ee7e5bd25346f5a on https://github.com/dubzzz/fast-check/pull/3554

**Comment by dubzzz** [comment]
It seems that only replays is doing something wrong. The usual runner still passes over the same values, fails with the same path and counter-example.
