### ISSUE TITLE
FC with Jest: Cannot read properties of undefined (reading 'generate')

### ISSUE THREAD

**Issue by gugakatsi** [dubzzz/fast-check#4277]
## 🐛 Bug Report

! https://codesandbox.io/p/sandbox/jovial-meninsky-ysjdkf?file=%2Findex.test.js%3A21%2C5 !

Clear and concise description of the bug.

Using  "jest": "^29.7.0" and "@fast-check/jest": "^1.7.3"

Running following test code 

```
const { test, fc } = require('@fast-check/jest');

const { MultiKeyValue } = require("../../../packages/hefe-node/utils/FEObjUtils");

describe('MultiKeyValue() getting bombed by random possible Keys and random possible Values', () => {
  test.prop(
    [
      fc.uniqueArray(fc.string({ minLength: 1 }), { maxLength: 55, minLength: 1 }),
      fc.oneof(fc.string(), fc.integer(), fc.object(), fc.boolean(), fc.array())
    ],
  )(
    'Just bombs args',
    (KeysArray, RandomValues) => {
      const multiKeyedValueObj = MultiKeyValue(KeysArray, RandomValues);
      const objKeys = Object.keys(multiKeyedValueObj);

      // expect(objKeys).toEqual(KeysArray);
      expect(objKeys).toEqual(Array.from(KeysArray))
    }
  )
});
```

Gives the following error:
```
Cannot read properties of undefined (reading 'generate')
TypeError: Cannot read properties of undefined (reading 'generate')
    at NoopSlicedGenerator.next (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/implementations/NoopSlicedGenerator.js:14:25)
    at ArrayArbitrary.generateNItems (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/ArrayArbitrary.js:86:45)
    at ArrayArbitrary.safeGenerateNItems (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/ArrayArbitrary.js:95:25)
    at ArrayArbitrary.generate (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/ArrayArbitrary.js:130:20)
    at FrequencyArbitrary.safeGenerateForIndex (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/FrequencyArbitrary.js:143:53)
    at FrequencyArbitrary.generate (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/FrequencyArbitrary.js:66:29)
    at AlwaysShrinkableArbitrary.generate (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/AlwaysShrinkableArbitrary.js:13:32)
    at TupleArbitrary.generate (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/arbitrary/_internals/TupleArbitrary.js:67:60)
    at AsyncProperty.generate (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/property/AsyncProperty.generic.js:28:32)
    at SkipAfterProperty.generate (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/property/SkipAfterProperty.js:35:30)
    at tossNext (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/runner/Tosser.js:10:22)
    at toss (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/runner/Tosser.js:17:15)
    at toss.next (<anonymous>)
    at SourceValuesIterator.next (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/runner/SourceValuesIterator.js:15:42)
    at RunnerIterator.next (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/runner/RunnerIterator.js:18:43)
    at asyncRunIt (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/fast-check/lib/check/runner/Runner.js:32:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.<anonymous> (/Users/gugakatsiashvili/Desktop/Headless-FileExplorer/node_modules/@fast-check/jest/lib/internals/TestWithPropRunnerBuilder.js:43:9)

```

MultiKeyValue func:

```
export const MultiKeyValue = (
  keys,
  value
) => {
  const obj = {};
  keys.forEach((key, i) => {
    obj[key] = value;
  });
  return obj;
};

```

Rest of the code is above

## Expected behavior

It should run the test without any errors 

If you have one, please provide a minimal repository reproducing the issue on GitHub.

https://codesandbox.io/p/sandbox/jovial-meninsky-ysjdkf?file=%2Findex.test.js%3A21%2C5

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| @fast-check/jest      |       "^1.7.3"     |
| node                 |        18.18.0    |

Other deps:
```
  "dependencies": {
    "@domql/utils": "latest",
    "babel-plugin-transform-flow-enums": "latest",
    "flow-enums-runtime": "latest"
  },
  "devDependencies": {
    "@babel/cli": "^7.23.0",
    "@babel/core": "^7.23.0",
    "@babel/plugin-transform-modules-commonjs": "^7.23.0",
    "@babel/preset-env": "^7.22.20",
    "@babel/preset-flow": "latest",
    "@fast-check/jest": "^1.7.3",
    "flow-bin": "latest",
    "jest": "^29.7.0"
  }
```

**
Strange thing is, even when i made sample for codesandbox, it ran fine on 1st run , but after that it fails with same error again and again
**

**Comment by dubzzz** [comment]
Not a bug, actually `fc.array()` need a parameter. In your case if what you want is any array just use `fc.array(fc.anything())`.

Note: TypeScript or any other type system would have detected the issue.

**Comment by gugakatsi** [comment]
Did you try codesandbox and it ran tests successfully? At a glance I can't understand, what is wrong with ```    fc.uniqueArray(fc.string()),
```  or ```    fc.uniqueArray(fc.string(), { ...stringParams }), ```

**Comment by gugakatsi** [comment]
Ah my bad , fc.array() here ```      fc.oneof(fc.string(), fc.integer(), fc.object(), fc.boolean(), fc.array())
```  ,  **I had empty fc.array() **
