### ISSUE TITLE
First digit dropped from path?!

### ISSUE THREAD

**Issue by hsommerlandreason** [dubzzz/fast-check#4339]
## 🐛 Bug Report

I have come across a hyperstrange bug.
When I try to replay a test with a path fast-check complains that it is a malformed path  but it reports the path with the first digit dropped.

## To Reproduce

I run the tests and it complains about:
```
  ● Cleanup (with seed=481321175)

    Property failed after 41 tests
    { seed: 481321175, path: "40:1:0:2:2:2:2:2:4:4:4:4:4:4:4:6:6:6:7:6:7:8:7:9:9:9:9:9:9:9:9:9:9:9:9:9:10:10:10:10:10:10:10
:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10
:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10", endOnFailure: true }
    Counterexample: [{"pairs":[["b","0.0.0"],["a","0.0.0"],["b","0.0.00"],["ba","0.0.0"],["a","0.0.0f0"]],"isIgnored":false
,"gen":[["b","0.0.00"]]}]
    Shrunk 113 time(s)
    Got error: expect(sinon.spy).toBeCalledWith()
```

I say gosh darnit and change the test to:
```typescript
const _path = "40:1:0:2:2:2:2:2:4:4:4:4:4:4:4:6:6:6:7:6:7:8:7:9:9:9:9:9:9:9:9:9:9:9:9:9:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10"

test.prop({
  pairs: fc.uniqueArray(
    fc.tuple(
      fc
        .stringOf(fc.constantFrom('a', 'b', '.'), { minLength: 1 })
        .filter((s) => s !== '__proto__' && s.trim() !== ''),
      fc.stringMatching(/^([0-9])\.([0-9]+)\.([0-9]+)(?:([dabf])([0-9]+))?$/)
    ),
    { minLength: 2, comparator: deepEqual }
  ),
  isIgnored: fc.boolean(),
  gen: fc.gen(),
}, {path: _path})('Cleanup', async ({ pairs, isIgnored, gen }) => { .... }
```

I then run:
```
grandmother@...<fix/device-chaos>$ npx jest --seed=481321175 testyfile.spec.ts 
  ● Cleanup (with seed=481321175)

    Unable to replay, got wrong path=0:1:0:2:2:2:2:2:4:4:4:4:4:4:4:6:6:6:7:6:7:8:7:9:9:9:9:9:9:9:9:9:9:9:9:9:10:10:10:10:10
:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10
:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10

      at pathWalk (../node_modules/fast-check/lib/check/runner/utils/PathWalker.js:17:19)
      at applyPath (../node_modules/fast-check/lib/check/runner/Runner.js:50:38)
      at check (../node_modules/fast-check/lib/check/runner/Runner.js:68:11)
      at Object.assert (../node_modules/fast-check/lib/check/runner/Runner.js:77:17)
      at Object.<anonymous> (../node_modules/@fast-check/jest/lib/internals/TestWithPropRunnerBuilder.js:43:18)

```

 Now this is the odd part: `got wrong path=0:1:0......`
 The path I provided begins with `40:1:0......`
 Where did the 4 go?🤷‍♂️ 

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
|fast-check | 3.13.1|
| node                 |  v18.16.0  (reproducable in node 20 as well)        |
| TypeScript         | 4.9.5          |

**Comment by dubzzz** [comment]
I can repro! Thanks a lot for the report, I'll investigate it!

**Comment by dubzzz** [comment]
Closing the issue for now.

The bug itself was about the path being wrongly reported. For now support for replays on `gen` is out-of-scope. I filled an issue to track the need but no short term plan to prioritize it given the huge impacts it may have on the API of arbitraries.
