### ISSUE TITLE
fc.float unexpectedly yields NaN

### ISSUE THREAD

**Issue by dmurvihill** [dubzzz/fast-check#4765]
## 🐛 Bug Report
```typescript
describe('float', () => {
  it('should not randomly give NaN', () => {
    fc.assert(fc.property(
      fc.float({ min: 0, max: 6000}), n => {
        expect(n).not.toEqual(NaN)
      }
    ), { seed: -1910245166, path: "66", endOnFailure: true });
  });
});
```

## To Reproduce

Steps to reproduce:
- Add the test above to `packages/fast-check/test/unit/arbitrary/float.spec.ts`
- `cd packages/fast-check`
- `yarn exec jest test/unit/arbitrary/float.spec.ts`

## Expected behavior

Should pass; instead:
```
  ● float › should not randomly give NaN

    Property failed after 1 tests
    { seed: -1910245166, path: "66", endOnFailure: true }
    Counterexample: [Number.NaN]
    Shrunk 0 time(s)
    Got error: expect(received).not.toEqual(expected) // deep equality

    Expected: not NaN

      56 |     fc.assert(fc.property(
      57 |       fc.float({ min: 0, max: 6000}), n => {
    > 58 |         expect(n).not.toEqual(NaN)
         |                       ^
      59 |       }
      60 |     ), { seed: -1910245166, path: "66", endOnFailure: true });
      61 |   });

      at toEqual (test/unit/arbitrary/float.spec.ts:58:23)
      at Property.p [as predicate] (lib/check/property/Property.js:17:86)
      at Property.predicate [as run] (lib/check/property/Property.generic.js:49:33)
      at run (lib/check/runner/Runner.js:21:30)
      at runIt (lib/check/runner/Runner.js:65:11)
      at Object.check (lib/check/runner/Runner.js:69:17)
      at Object.assert (test/unit/arbitrary/float.spec.ts:56:8)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (lib/check/runner/utils/RunDetailsFormatter.js:131:15)
      at buildError (lib/check/runner/utils/RunDetailsFormatter.js:143:11)
      at throwIfFailed (lib/check/runner/utils/RunDetailsFormatter.js:156:16)
      at Object.assert (lib/check/runner/Runner.js:73:51)
      at Object.assert (test/unit/arbitrary/float.spec.ts:56:8)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 16 passed, 17 total
Snapshots:   0 total
Time:        4.552 s
Ran all test suites matching /test\/unit\/arbitrary\/float.spec.ts/i.
```

**Comment by gruhn** [comment]
The Arbitrary has a parameter for that: 

    fc.float({ min: 0, max: 6000, noNaN: true })

See: https://fast-check.dev/api-reference/interfaces/FloatConstraints.html#noNaN

**Comment by dubzzz** [comment]
Closing as expected
