### ISSUE TITLE
RangeError: Maximum call stack size exceeded while shrinking an array of integers

### ISSUE THREAD

**Issue by vicrac** [dubzzz/fast-check#499]
## 🐛 Bug Report

Running test involving generating large arrays of integers results in:
```
    RangeError: Maximum call stack size exceeded

      at IntegerArbitrary.Object.<anonymous>.ArbitraryWithShrink.shrinkableFor (node_modules/fast-check/lib/check/arbitrary/definition/ArbitraryWithShrink.js:11:60)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:62:35)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
      at ArrayArbitrary.Object.<anonymous>.ArrayArbitrary.shrinkImpl (node_modules/fast-check/lib/check/arbitrary/ArrayArbitrary.js:68:20)
``` 

### Steps to reproduce:
1. Run the following test several times:
```
import * as fc from "fast-check";

test("returning NaN from compare function shouldn't alter the order of elements", () => {
  fc.assert(
    fc.property(fc.array(fc.integer(), 10000), data => {
      const sortedWithNaN = [...data].sort((a, b) => NaN);
      expect(data).toEqual(sortedWithNaN);
    })
  );
});
```

## Expected behavior

Test should not end with Exception thrown by `fast-check`.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |      1.20.0      |
| node                  |     v10.16.0       |
| TypeScript           |      3.7.3      |

**Comment by dubzzz** [comment]
Thanks a lot for the report.

There is indeed a real bug there, I'll need to check how I can get it work 🤔

By the way, just in case: by using `fc.array(fc.integer(), 10000).noShrink()` you'll be able to completely remove the shrink capabilities of the array - _it's clearly not a valid fix or workaround_.

Potential solutions that came to my mind (not implemented yet):
- add a parameter to `noShrink()` in order to define the maximal shrinking depth - or add another method just for that need
- add a setting to `fc.assert` to define the maximal shrinking depth
- both (we have currently `noShrink()` at arbitrary level and `endOnFailure` at assert level)

**Comment by dubzzz** [comment]
Here is a potential workaround in order to unlock you:

_TypeScript version_
```ts
class ShrinkLimitedArbitrary<T> extends fc.Arbitrary<T> {
  constructor(private readonly arb: fc.Arbitrary<T>, private readonly maxDepth: number) {
    super();
  }

  private static wrapShrinkable<T>(s: fc.Shrinkable<T>, remainingDepth: number): fc.Shrinkable<T> {
    if (remainingDepth <= 0) {
      return new fc.Shrinkable(s.value_);
    }
    return new fc.Shrinkable(s.value_, () => {
      return s.shrink().map(i => ShrinkLimitedArbitrary.wrapShrinkable(i, remainingDepth - 1));
    });
  }

  generate(mrng: fc.Random): fc.Shrinkable<T> {
    return ShrinkLimitedArbitrary.wrapShrinkable(this.arb.generate(mrng), this.maxDepth);
  }
}

const shrinkLimiter = <T>(arb: fc.Arbitrary<T>, maxDepth: number): fc.Arbitrary<T> => {
  return new ShrinkLimitedArbitrary(arb, maxDepth);
};
```

_JavaScript version_
```js
class ShrinkLimitedArbitrary extends fc.Arbitrary {
  constructor(arb, maxDepth) {
    super();
    this.arb = arb;
    this.maxDepth = maxDepth;
  }

  static wrapShrinkable(s, remainingDepth) {
    if (remainingDepth <= 0) {
      return new fc.Shrinkable(s.value_);
    }
    return new fc.Shrinkable(s.value_, () => {
      return s.shrink().map(i => ShrinkLimitedArbitrary.wrapShrinkable(i, remainingDepth - 1));
    });
  }

  generate(mrng) {
    return ShrinkLimitedArbitrary.wrapShrinkable(this.arb.generate(mrng), this.maxDepth);
  }
}

const shrinkLimiter = (arb, maxDepth) => {
  return new ShrinkLimitedArbitrary(arb, maxDepth);
};
```

Your snippet can now be:

```js
import * as fc from "fast-check";

test("returning NaN from compare function shouldn't alter the order of elements", () => {
  fc.assert(
    fc.property(shrinkLimiter(fc.array(fc.integer(), 10000), 3), data => {
      const sortedWithNaN = [...data].sort((a, b) => NaN);
      expect(data).toEqual(sortedWithNaN);
    })
  );
});
```

**Comment by dubzzz** [comment]
@vicrac Issue should be fixed with the latest release of fast-check (>=1.22.1). Do you confirm?

**Comment by vicrac** [comment]
@dubzzz yes, i run it and it seems to no longer reoccur :smile: Thanks for help!
