### ISSUE TITLE
Frequent "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by markandrus** [dubzzz/fast-check#5218]
## 🐛 Bug Report

I have an AST that I've generated fast-check Arbitrary instances for. The AST is recursive so I've stuck them all in an `fc.letrec` and `tie` them off. There are currently a little over 100 entries in the `fc.letrec` (not sure if this is relevant), and the AST itself can go pretty deep.

When using the Arbitrary, I often see

```
    RangeError [Error]: Maximum call stack size exceeded
        at Value (file://redacted/node_modules/fast-check/lib/esm/check/arbitrary/definition/Value.js:4:16)
        at ConstantArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/ConstantArbitrary.js:15:20)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at MapArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/check/arbitrary/definition/Arbitrary.js:87:28)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:63:29)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
```

```
    RangeError [Error]: Maximum call stack size exceeded
        at Random.nextInt (file://redacted/node_modules/fast-check/lib/esm/random/generator/Random.js:15:12)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:60:31)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at MapArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/check/arbitrary/definition/Arbitrary.js:87:28)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:63:29)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
```

```
    RangeError [Error]: Maximum call stack size exceeded
        at FrequencyArbitrary.mustGenerateFirst (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:148:22)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:57:18)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:63:29)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at MapArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/check/arbitrary/definition/Arbitrary.js:87:28)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
```

```
    RangeError [Error]: Maximum call stack size exceeded
        at unsafeUniformArrayIntDistributionInternal (file://redacted/node_modules/pure-rand/lib/esm/distribution/internals/UnsafeUniformArrayIntDistributionInternal.js:2:58)
        at uniformLargeIntInternal (file://redacted/node_modules/pure-rand/lib/esm/distribution/UnsafeUniformIntDistribution.js:20:5)
        at unsafeUniformIntDistribution (file://redacted/node_modules/pure-rand/lib/esm/distribution/UnsafeUniformIntDistribution.js:29:12)
        at Random.nextInt (file://redacted/node_modules/fast-check/lib/esm/random/generator/Random.js:16:16)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:60:31)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:63:29)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
```

```
    RangeError [Error]: Maximum call stack size exceeded
        at uniformLargeIntInternal (file://redacted/node_modules/pure-rand/lib/esm/distribution/UnsafeUniformIntDistribution.js:9:33)
        at unsafeUniformIntDistribution (file://redacted/node_modules/pure-rand/lib/esm/distribution/UnsafeUniformIntDistribution.js:29:12)
        at Random.nextInt (file://redacted/node_modules/fast-check/lib/esm/random/generator/Random.js:16:16)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:60:31)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at TupleArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/TupleArbitrary.js:63:45)
        at MapArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/check/arbitrary/definition/Arbitrary.js:87:28)
        at LazyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/LazyArbitrary.js:12:32)
        at FrequencyArbitrary.safeGenerateForIndex (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:140:53)
        at FrequencyArbitrary.generate (file://redacted/node_modules/fast-check/lib/esm/arbitrary/_internals/FrequencyArbitrary.js:63:29)
```

## To Reproduce

Here is a simplified version of the Arbitrary that I generated. Suppose it's always picking cases to generate that recurse, leading to very deep trees. Is there some way to influence the branches it takes? Maybe sorting the cases so that the least recursive cases appear first in the union?

```ts
const { cases: testArb } = fc.letrec(tie => ({
  cases: fc.oneof(
    tie('case1'),
    tie('case2'),
    tie('case3'),
    tie('case4'),
    tie('case5'),
    tie('case6'),
    tie('case7'),
    tie('case8'),
    tie('case9'),
    tie('case10'),
    tie('case11'),
    tie('case12'),
    tie('case13'),
    tie('case14'),
    tie('case15'),
    tie('case16'),
    tie('case17'),
    tie('case18'),
    tie('case19'),
    tie('case20'),
    tie('case21'),
    tie('case22'),
    tie('case23')
  ),
  case1: fc.record({
    a: fc.option(tie('cases')),
    b: fc.array(fc.tuple(tie('cases'), tie('cases')), { minLength: 1 })
  }),
  case2: fc.record({
    a: tie('cases')
  }),
  case3: fc.constant({}),
  case4: fc.record({
    a: tie('cases')
  }),
  case5: fc.record({
    a: tie('cases')
  }),
  case6: fc.record({
    a: tie('cases'),
    b: tie('cases'),
    c: fc.option(tie('cases'))
  }),
  case7: fc.record({
    a: tie('cases')
  }),
  case8: fc.record({
    a: fc.array(tie('cases')),
    b: fc.oneof(fc.record({
      a: tie('cases')
    }), fc.constant({}))
  }),
  case9: fc.record({
    a: fc.array(tie('cases')),
    b: fc.array(tie('cases'))
  }),
  case10: fc.constant({}),
  case11: fc.record({
    a: tie('cases'),
    b: tie('cases')
  }),
  case12: fc.record({
    a: tie('cases')
  }),
  case13: fc.record({
    a: tie('cases')
  }),
  case14: fc.record({
    a: tie('cases'),
    b: tie('cases')
  }),
  case15: fc.record({
    a: tie('cases'),
    b: tie('cases'),
    c: tie('cases')
  }),
  case16: fc.record({
    a: tie('cases'),
    b: tie('cases'),
    c: tie('cases')
  }),
  case17: fc.record({
    a: tie('cases')
  }),
  case18: fc.constant({}),
  case19: fc.constant({}),
  case20: fc.record({
    a: fc.array(tie('cases'), { minLength: 1 })
  }),
  case21: fc.record({
    a: fc.array(tie('cases'))
  }),
  case22: fc.constant({})
}))
```

## Expected behavior

fast-check should never generate a "Maximum call stack size exceeded" error.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           | 3.21.0     |
| node                 | v22.6.0    |
| TypeScript\*         | 5.4.5      |

\*Only for TypeScript's users

**Comment by markandrus** [comment]
The problem was my first entry of the `fc.oneof`. It was always recursive. I reordered my `fc.oneof` so that the first Arbitrary is not recursive.

Thank you for this library! 👋
