### ISSUE TITLE
Possible error in double

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#5494]
## 🐛 Bug Report

Found by CI:

```txt
  FAIL  test/unit/arbitrary/double.spec.ts > double (integration) > should only produce correct values
Error: Property failed after 63 tests
{ seed: 294206129, path: "62:1:2:6:2:1:1:0:1:1:0:3:3:1:0:0:5:7", endOnFailure: true }
Counterexample: [-2048281109,2,Stream(…),{"min":1.340782071662466e+154,"noDefaultInfinity":true,"noNaN":true,"minExcluded":true}]
Shrunk 17 time(s)
Got error: Expect: 1.7976931348623157e+308 to be a correct value

Got error: AssertionError: expected 1.7976931348623157e+308 not to be 1.7976931348623157e+308 // Object.is equality
    at assertCorrectness (/home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:311:11)
    at /home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:102:13
    at Property.predicate (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/property/Property.js:14:54)
    at Property.run (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/property/Property.generic.js:46:33)
    at runIt (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/runner/Runner.js:18:30)
    at check (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/runner/Runner.js:62:11)
    at Module.assert (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/runner/Runner.js:65:17)
    at assertProduceCorrectValues (/home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:88:6)
    at /home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/double.spec.ts:343:5
    at file:///home/runner/.yarn/berry/cache/@vitest-runner-npm-2.1.6-6238f71787-10c0.zip/node_modules/@vitest/runner/dist/index.js:146:14
```

**Comment by gruhn** [comment]
I tried to reproduce this, but on `main` the test passes (with same seed and path). I could reproduce it though for commits closer to Dec 6. So I used `git bisect` to narrow it down and it turns out 8a09008fe02da06c8659b86d2ff0ad17951cab24 is the first commit where the test starts to pass. The commit is modifying the `double` arbitrary, so that makes sense. But not sure if this means that the commit really fixed whatever issue was there or if the seed+path combination can't reproduce the issue anymore after modifying the arbitrary.

**Comment by dubzzz** [comment]
I'll try to re-run "should only produce correct values" a lot of times just to see if we fixed it with the move to BigInt.

**Comment by dubzzz** [comment]
Thank you so much for the investigation, you saved me precious time with it and with all the other contributions you did 🤗
