### ISSUE TITLE
Issue on jsonValue to be checked 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#5519]
## 💥 Regression Report

https://github.com/dubzzz/fast-check/actions/runs/12306265865/job/34347724793#step:9:1

```txt
FAIL  test/unit/arbitrary/jsonValue.spec.ts > jsonValue (integration) > should only produce correct values
Error: Property failed after 35 tests
{ seed: -1477621317, path: "34", endOnFailure: true }
Counterexample: [1249453856,undefined,Stream(17,0,19,20,11,4,16,10,4,13,8,0,5,14,2,11,8,16,16,19,13,16,16…),{"maxDepth":5,"noUnicodeString":true,"stringUnit":"binary-ascii"}]
Shrunk 0 time(s)
Got error: Expect: {"\u0000":false,"\\[":false} to be a correct value

Got error: AssertionError: expected { '\u0000': false, '\\\': false } to deeply equal { '\u0000': false, '\\[': false }
    at assertCorrectness (/home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:311:11)
    at /home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:102:13
    at Property.predicate (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/property/Property.js:14:54)
    at Property.run (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/property/Property.generic.js:46:33)
    at runIt (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/runner/Runner.js:18:30)
    at check (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/runner/Runner.js:62:11)
    at Module.assert (/home/runner/work/fast-check/fast-check/packages/fast-check/lib/esm/check/runner/Runner.js:65:17)
    at Module.assertProduceCorrectValues (/home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts:88:6)
    at /home/runner/work/fast-check/fast-check/packages/fast-check/test/unit/arbitrary/jsonValue.spec.ts:64:5
    at file:///home/runner/.yarn/berry/cache/@vitest-runner-npm-2.1.8-b6a852e96f-10c0.zip/node_modules/@vitest/runner/dist/index.js:146:14

Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
```

**Comment by gruhn** [comment]
Hmm, this one I can't reproduce at all. The job ran on the branch [rundetails-format](https://github.com/dubzzz/fast-check/tree/refs/heads/rundetails-format) which doesn't exist anymore. Presumably, it was [this PR](https://github.com/dubzzz/fast-check/pull/5517). But checked out e2779623c530ce7ac8ff9b65896503075eb2fd16 where this PR was merged but even there I can't reproduce this issue (with the same seed+path).

**Comment by dubzzz** [comment]
Then maybe worth closing for now. It never happened again
