### ISSUE TITLE
Fix failing test "anything / Should shrink towards minimal value of type"

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#84]
Failure of test "anything / Should shrink towards minimal value of type" with seed=1525284770005 and path=67

```
  1) ObjectArbitrary
       anything
         Should shrink towards minimal value of type:
     Property failed after 68 tests (seed: 1525284770005, path: 67): [254558566]
Shrunk 0 time(s)
Got error: AssertionError [ERR_ASSERTION]: Should have shrinked towards zero
Stack trace: AssertionError [ERR_ASSERTION]: Should have shrinked towards zero
    at assertShrinkedValue (/home/travis/build/dubzzz/fast-check/test/unit/check/arbitrary/ObjectArbitrary.spec.ts:41:23)
    at /home/travis/build/dubzzz/fast-check/test/unit/check/arbitrary/ObjectArbitrary.spec.ts:119:11
    at Property.predicate (/home/travis/build/dubzzz/fast-check/src/check/property/Property.generated.ts:271:28)
    at Property.run (/home/travis/build/dubzzz/fast-check/src/check/property/Property.generic.ts:15:27)
    at runIt (/home/travis/build/dubzzz/fast-check/src/check/runner/Runner.ts:19:28)
    at check (/home/travis/build/dubzzz/fast-check/src/check/runner/Runner.ts:74:7)
    at Object.assert (/home/travis/build/dubzzz/fast-check/src/check/runner/Runner.ts:81:15)
    at Context.<anonymous> (/home/travis/build/dubzzz/fast-check/test/unit/check/arbitrary/ObjectArbitrary.spec.ts:111:10)
    at callFn (/home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runnable.js:383:21)
    at Test.Runnable.run (/home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runnable.js:375:7)
    at Runner.runTest (/home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runner.js:446:10)
    at /home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runner.js:564:12
    at next (/home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runner.js:360:14)
    at /home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runner.js:370:7
    at next (/home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/travis/build/dubzzz/fast-check/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

Build result: https://travis-ci.org/dubzzz/fast-check/jobs/374062754

**Comment by dubzzz** [comment]
The problem was caused by:
```assert.strictEqual(-0, 0)```

which is now considered false ;)
